package day05;

public class Test06 {

	public static void main(String[] args) {
		
		System.out.println(Calc.add(1, 2));
		System.out.println(Calc.add(1.5, 2.0));
		
	}

}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     